### ISSUE TITLE
Remove comments from json files

### ISSUE THREAD

**Issue by MattPitlyk** [anthonyeden/Azure-Functions-Python-HTTP-Example#1]
This example is great, but I recommend removing the comments from host.json. Comments are not valid in json files and it's recommended to remove them (see bold in link below). It tripped me up for a while, and I'd like to save others from the same headache.
https://github.com/Azure/azure-webjobs-sdk-script/wiki/host.json

**Comment by anthonyeden** [comment]
Hi @MattPitlyk,

Good pickup. All sorted.
